### ISSUE TITLE
[Bug]: Unable to add chart dependency

### ISSUE THREAD

**Issue by msanand** [amikos-tech/chromadb-chart#54]
### What happened?

Hi,

Installing chroma chart by adding it to the helm repo and doing a helm install, as described in your README works fine.
`helm repo add chroma https://amikos-tech.github.io/chromadb-chart/`

But when I add chroma as a dependency to my Chart.yaml and do a `helm dependency update`, I get an error saying 
`Error: Chart.yaml file missing`

I added the dependency this way in my Chart.yaml:
```
dependencies:
  - name: chromadb
    version: 0.1.19
    repository: "https://amikos-tech.github.io/chromadb-chart/"
```

I also tried using the name of the repo I had added 'helm repo add chroma https://amikos-tech.github.io/chromadb-chart/` but that gave the same error.

```
dependencies:
  - name: chromadb
    version: 0.1.19
    repository: "@chroma"
```

Am I missing something here? Or is there an issue with pulling this chart as a dependency into my chart? Appreciate your support. Thanks!

### ChromaDB Version

0.4.3

### Kubernetes Version

1.27.x

### Environment details

local k8s cluster

### Logs, Kubectl output, Manifests, etc.

```shell
Error: Chart.yaml file is missing
```

**Comment by tazarov** [comment]
@msanand, thanks for reporting this. I will have a look

**Comment by tazarov** [comment]
hey @msanand,

I've just tested with the following:

```bash
helm create my-test-chart
```
Then edited `Chart.yaml`:

```yaml
apiVersion: v2
name: my-test-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: chromadb
    version: 0.1.19
    repository: "https://amikos-tech.github.io/chromadb-chart/"

```

and finally updated dependencies (from the helm repo):

```bash
[my-test-chart] helm dependency update                                                                                                                                                                                                                                                                                11:25:16  ☁  main ☂ ⚡ ✭
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "chromadb" chart repository
...Successfully got an update from the "dapr" chart repository
...Successfully got an update from the "dapr-repo" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "chroma" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading chromadb from repo https://amikos-tech.github.io/chromadb-chart/
Deleting outdated charts
```

As a result the chromad db chart is under `charts`:

![image](https://github.com/user-attachments/assets/a2f52677-720b-4d33-8a1b-78bf04ecf919)


Let me know if these are the steps you followed?
